# Generated by Django 4.0.10 on 2024-03-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_invoice_revenue_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='revenue_source',
            field=models.CharField(max_length=255),
        ),
    ]
